import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import { Header } from '@/components/layout/Header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='cmn-container bg-opacity-50 p-10 pt-28 min-h-screen overflow-hidden relative before:fixed before:w-full before:h-full before:z-20 before:inset-0 before:pointer-events-none md:min-w-[1200px]'>
        <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
